<?php
# $Id: en-GB.com_livingword.ini 3.0.0 2014-03-18 13:35:50Z ml $      
# Author LivingWord Project      
# Author Email web@mlwebtechnologies.com      
# Copyright (C) 2008-2014 Mike Leeper - MLWebTechnologies. All rights reserved.      
# License http://www.gnu.org/licenses/gpl-3.0.html GNU/GPL      
# Language English (EN)     
# Note : All ini files need to be saved as UTF-8 - No BOM            
define('LWTITLE','LivingWord');
define('LWPRINT','Print');
define('INTROMSG','The Bible is the most remarkable collection ever written.<br />Over a period of two thousand years; in times of war and peace.  Written by kings, physicians, tax collectors, farmers, fishermen, singers, and shepherds.  Written in three languages - Hebrew, Aramaic, and Greek.  Such a diverse group of writers, yet this cohesive unity is inspired and perfected by the Holy Spirit Himself.  Jesus Christ is the grand subject, our good is its design, and the glory of God is its end.<br /><br />&quot;Breathing life into all who believe...The Word is alive!&quot;  (<small><a href=&quot;http://www.castingcrowns.com&quot; target=&qout;_new&quot;>Casting Crowns</a> - Word is Alive</small>)<br /><br /><i><small>&quot;All Scripture is inspired by God and profitable for teaching, for reproof, for correction, for training in righteousness; that the man of God may be adequate, equipped for every good work.&quot; <b><a href=&quot;http://www.biblegateway.com/passage/?search=2Tim+3:16-17;&version=51;&interface=print&quot; target=&quot;_new&quot;>2 Tim. 3:16-17</a></small></i></b>');
define('COMPMSG','With this plan, you will read the bible, from cover to cover, from Genesis to Revelation.<br /><br /><br /><br /><br /><small><i>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </i><b><a href=&quot;http://www.biblegateway.com/passage/?search=Hebrews+4:12;&version=51;&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></b></small><br />');
define('THRUMSG','With this plan, you will read each day from the Old Testament, New Testament, Psalms, and Proverbs. Gain understanding of how God\'s Word is tied together.<br /><br /><br /><br /><small><i>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </i><b><a href=&quot;http://www.biblegateway.com/passage/?search=Hebrews+4:12;&version=51;&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></b></small><br /><br />');
define('NEWTESTMSG','With this plan, you will read each day from the New Testament.<br /><br /><br /><br /><small><i>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </i><b><a href=&quot;http://www.biblegateway.com/passage/?search=Hebrews+4:12;&version=51;&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></b></small><br /><br />');
define('SURVMSG','With this plan, you will read with an emphasis on key passages of the bible.<br /><br /><br /><br /><br /><small><i>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </i><b><a href=&quot;http://www.biblegateway.com/passage/?search=Hebrews+4:12;&version=51;&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></b></small><br />'); 
define('BIOMSG','With this plan, you will read with an emphasis on key figures of the bible.<br /><br /><br /><br /><br /><small><i>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </i><b><a href=&quot;http://www.biblegateway.com/passage/?search=Hebrews+4:12;&version=51;&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></b></small><br />'); 
define('CHRONMSG','With this plan, you will read with an emphasis on key stories of the bible in a chronological order.<br /><br /><br /><br /><br /><small><i>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </i><b><a href=&quot;http://www.biblegateway.com/passage/?search=Hebrews+4:12;&version=51;&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></b></small><br />'); 
define('ONTPMSG','With this plan, you will read the Bible from cover to cover, from Genesis to Revelation.<br /><br /><br /><br /><small><em>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </em><strong><a href=&quot;http://classic.biblegateway.com/passage/?search=Hebrews 4:12&version=51&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></strong></small>');
define('OLDTESTMSG','With this plan, you will read each day from the Old Testament.<br /><br /><br /><small><em>&quot;For the word of God is living and active. Sharper than any double-edged sword, it penetrates even to dividing soul and spirit, joints and marrow; it judges the thoughts and attitudes of the heart&quot;. </em><strong><a href=&quot;http://classic.biblegateway.com/passage/?search=Hebrews 4:12&version=51&interface=print&quot; target=&quot;_new&quot;>Hebrews 4:12</a></strong></small><br /><br />');
define('SETMSG','Here you can set your own personal preferences for bible reading. You can choose a bible plan, version, and audio version.  You can also choose to receive daily email reminders with your reading selection for that day. You can even choose the day you would like to start your reading plan.<br /><br /><br /><i><small>&quot;Every word of God is flawless; He is a shield to those who take refuge in Him.&quot; <b><a href=&quot;http://www.biblegateway.com/passage/?search=Psalm+30:5;&version=51;&interface=print&quot; target=&quot;_new&quot;>Psalm 30:5</a></small></i></b><br />');
define('TOOLMSG','Here are tools to help with your bible study. The Bible Dictionary can be searched according to keywords with matching criteria or it can be searched by general alphabetical index. Bible commentaries can be viewed according to each book of the bible.  Several commentator sources are available for each. Lexicon references are available for those who are studying the original Greek and Hebrew translations of the Old and New Testaments.<br /><br /><i><small>&quot;Every word of God is flawless; He is a shield to those who take refuge in Him.&quot; <b><a href=&quot;http://www.biblegateway.com/passage/?search=Psalm+30:5;&version=51;&interface=print&quot; target=&quot;_new&quot;>Psalm 30:5</a></small></i></b>'); 
define('RESMSG','Here is a list of additional bible study resources. These resources, listed by age group, will help with your study of the bible and build your understanding of God\'s Word.<br /><br /><br /><i><small>&quot;As for God, His way is perfect; the word of the Lord is flawless.  He is a shield for all who take refuge in Him.&quot;<b><a href=&quot;http://www.biblegateway.com/passage/?search=Psalm+18:30;&version=51;&interface=print&quot; target=&quot;_new&quot;> Psalm 18:30</a></small></i></b><br /><br /><i><small>&quot;Thy word is a lamp unto my feet, and a light unto my path.&quot;<b><a href=&quot;http://www.biblegateway.com/passage/?search=Psalm+119:105;&version=51;&interface=print&quot; target=&quot;_new&quot;> Psalm 119:105</a></small></i></b>');
define('BPLABEL','Bible Plan:');
define('BVLABEL','Bible Version:');
define('PBVLABEL','Parallel Bible Version:');
define('AVLABEL','Alternate Audio Version:');
define('PVLABEL','Plan View:');
define('EMLABEL','Email Reminders:');
define('ALTPLANVIEWLABEL','Alternate Full Plan View');
define('SELECTALTPLANVIEW','Select View');
define('SELECTALTPLANVIEWOPT1','List');
define('SELECTALTPLANVIEWOPT2','Calendar');
define('ALTDATELABEL','Plan Start Date:');
define('ALTLESSONLABEL','Alternate Lesson Start:');
define('SELECTBP','Select a Reading Plan');
define('SELECTBV','Select a Bible Version');
define('SELECTPV','Select a Parallel Bible Version');
define('SELECTAV','Select an Audio Version');
define('SELECTSD','Enter a Plan Start Date');
define('SELECTDICT','Please select a dictionary.');
define('SELECTCRIT','Please select a search criteria.');
define('SELECTKW','Enter Keywords');
define('SELECTKWS','Please enter a keyword to search.');
define('SELECTCOM','Please select a commentator.');
define('SELECTALTDATE','Select Date');
define('COMPPLAN','Comprehensive Reading Plan (365 days)');
define('THRUPLAN','Through-the-Bible Reading Plan (365 days)');
define('BIOPLAN','Biographical Reading Plan (121 days)');
define('SURVPLAN','Survey Reading Plan (61 days)');
define('CHRONPLAN','Chronological Reading Plan (61 days)');
define('NEWTESTPLAN','New Testament Reading Plan (83 days)');
define('ONTPPLAN','Old/New Testament Plan (365 days)');
define('OLDTESTPLAN','Old Testament Plan (282 days)');
define('LWPSET','User Preferences');
define('DAY','Day&nbsp;'); 
define('LWHOMEM','LivingWord Home');
define('LWHOME','Home');
define('LWTOOLS','Study Tools');
define('LWEMAILSUBJECT','Your daily scripture reading');
define('LWEMAILMSG','Hello %name%,\n\nTodays reading is from %link%.\n\n\n\nTo modify your settings, please visit %sitelink%\n\n\nThis message was generated by the LivingWord component on %title%\n\n<small><i>&quot;For the word of God is living and active. Sharper than any double-edged sword,\nit penetrates even to dividing soul and spirit, joints and marrow; it judges the<br />thoughts and attitudes of the heart&quot;. </i><b>Hebrews 4:12</b></small>');
define('LWSUBMIT','Submit');
define('LWNOTAUTH','You are not authorized to view this resource.');
define('LWDOLOGIN','You need to <a href=&quot;index.php?option=com_users&view=login&quot; target=&quot;_self&quot;>login</a> or <a href=&quot;index.php?option=com_users&view=registration&quot; target=&quot;_self&quot;>register</a> for a new account.');
define('LWRESOURCES','Bible Resources');
define('LWMENU','Menu');
define('LWBIBLESTUDY','Bible Study');
define('LW4TEENS','For Teens');
define('LW4KIDS','Just For Kids');
define('LWVIEWBP','View Bible Plan');
define('LWPASSDICTSEARCH','Bible Passage and Dictionary Search');
define('LWSEARCH1','Passage Lookup');
define('LWSEARCH2','Keyword Search');
define('LWSEARCH3','Topical Index');
define('LWSEARCH4','Dictionary Search');
define('LWSEARCH1ALT','Look for a passage in one or more Bible versions');
define('LWSEARCH2ALT','Look for keywords or phrases in one or more Bible versions');
define('LWSEARCH3ALT','Search the Bible by topic');
define('LWSEARCH4ALT','Search a Bible dictionary to provide additional insight into the Bible');
define('LWLEXICON1','Old/New Testament Greek');
define('LWLEXICON2','Old Testament Hebrew');
define('LWLEXICON1ALT','This lexicon has been developed to aid the user in understanding the original text of the Greek Old and New Testament.');
define('LWLEXICON2ALT','This lexicon has been developed to aid the user in understanding the original text of the Hebrew Old Testament.');
define('LWBIBLECOM','Bible Commentary');
define('LWSELECTCOM','Select a Commentator');
define('LWLEXICON','Lexicons');
define('LWVIEWFULLPLAN','View Full Reading Plan');
define('LWTODAYSREADING','Today\'s reading is from');
define('LWSETTINGSSAVED','Your preferences have been saved');
define('LWDBREADING','LivingWord Daily Bible Reading');
define('LWRSSFEEDTOPIC','Daily Bible Reading');
define('LWRSSFEEDMSG','This feed provides you with a daily bible reading');
define('USRLLWFEEDS','LivingWord Feeds'); 
define('LWPOWERBY','Powered by Joomla!, LivingWord, and BibleGateway'); 
define('LWBROUGHTBYML','LivingWord brought to you by&nbsp;');
define('LWBROUGHTBYBG','Bible resources brought to you by&nbsp;');
define('LWICAL','iCalendar');
define('LWYES','Yes');
define('LWNO','No');
define('LWCOMNOTINSTALL','LivingWord Component Not Installed');
define('LWBMSHAREPLAN','Share This Bible Reading Plan');
define('LWBMSHAREREADING','Share Today\'s Bible Reading');
define('LWEBIBLES','Non English Bibles in PDF Format');
define('LW_DISPLAY_NUM','Display #');
define('LWPLANNOTBEGIN','Your Bible reading plan has not yet begun');
define('LWCALNEXTMON','Next Month >>');
define('LWCALPREVMON','<< Previous Month');
define('LWSPECIALRESOURCES','Special Resources');
define('LWCOMMENTALT','Read commentary on');
define('SELECTTIME','Select Time');
?>